# Generated by Django 4.1.1 on 2022-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komentarze', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='tekst',
            field=models.CharField(max_length=400),
        ),
    ]
