# Generated by Django 4.1.1 on 2022-11-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stoisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoisko_id', models.IntegerField()),
                ('rodzaj_stoiska', models.CharField(max_length=25)),
                ('czy_aktywne', models.BinaryField()),
                ('opis_stanowiska', models.CharField(max_length=256)),
                ('ocena', models.PositiveIntegerField()),
            ],
        ),
    ]
