# Generated by Django 4.1.1 on 2022-12-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_stoiska', models.PositiveSmallIntegerField(choices=[(1, 'Inne'), (2, 'Żywność'), (3, 'Ciuchy')], default=1)),
                ('czy_aktywne', models.BooleanField()),
                ('opis_stanowiska', models.CharField(max_length=256)),
                ('krotki_opis', models.CharField(default='Krótki opis stanowiska', max_length=60)),
                ('zdjecie', models.ImageField(upload_to='stoiska_zdjecia')),
                ('wspolrzedne_x', models.FloatField()),
                ('wspolrzedne_y', models.FloatField()),
                ('sprzedawca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sprzedawca')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_produktu', models.CharField(max_length=40)),
                ('nazwa_stoiska', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoisko.stoisko')),
            ],
        ),
    ]
