# Generated by Django 4.1.1 on 2022-11-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stoisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_stoiska', models.CharField(max_length=25)),
                ('czy_aktywne', models.BooleanField()),
                ('opis_stanowiska', models.CharField(max_length=256)),
                ('krotki_opis', models.CharField(default='Krótki opis stanowiska', max_length=40)),
                ('ocena', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_produktu', models.CharField(max_length=40)),
                ('rodzaj_produktu', models.CharField(max_length=25)),
                ('ilosc', models.IntegerField()),
                ('nazwa_stoiska', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoisko.stoisko')),
            ],
        ),
    ]
