# Generated by Django 4.1.1 on 2022-11-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoisko',
            name='ocena',
        ),
    ]
