# Generated by Django 4.1.1 on 2022-11-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sprzedawcaprofile_user'),
        ('stoisko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoisko',
            name='sprzedawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sprzedawca'),
        ),
    ]
