# Generated by Django 4.1.1 on 2022-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0004_alter_stoisko_rodzaj_stoiska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoisko',
            name='rodzaj_stoiska',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inne'), (2, 'Żywność'), (3, 'Ciuchy'), (4, 'Akcesoria')], default=1),
        ),
    ]
