# Generated by Django 4.1.1 on 2022-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0005_alter_stoisko_rodzaj_stoiska'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoisko',
            name='zdjecie',
            field=models.ImageField(default='hello', upload_to='stoiska_zdjecia'),
            preserve_default=False,
        ),
    ]
