# Generated by Django 4.1.1 on 2022-11-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0006_stoisko_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoisko',
            name='zdjecie',
            field=models.ImageField(upload_to='media/stoiska_zdjecia'),
        ),
    ]
