# Generated by Django 4.1.1 on 2022-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0007_alter_stoisko_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoisko',
            name='zdjecie',
            field=models.ImageField(upload_to='stoiska_zdjecia'),
        ),
    ]
