# Generated by Django 4.1.1 on 2022-11-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0008_alter_stoisko_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='ilosc',
        ),
    ]
