# Generated by Django 4.1.1 on 2022-11-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoisko', '0009_remove_produkt_ilosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoisko',
            name='rodzaj_stoiska',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inne'), (2, 'Żywność'), (3, 'Ciuchy')], default=1),
        ),
    ]
